# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CICD App Keren

on:
  push:
    branches: [ "master" ]

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Test
      run: go test -v ./...

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Image and Push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: adhithia21/app-keren:${{ github.run_number }}

  deploy-container:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    
    - name: provission server via ssh
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_KEY }}
        script: |
          docker login --username=${{ secrets.DOCKERHUB_USERNAME }} --password=${{ secrets.DOCKERHUB_TOKEN }}
          docker pull adhithia21/app-keren:${{ github.run_number }}
          docker stop app-keren
          docker rm -f app-keren
          docker run --name app-keren -d -p 80:8000 adhithia21/app-keren:${{ github.run_number }}